# Generated by Django 4.2.20 on 2025-04-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=10000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vol_images/')),
            ],
        ),
    ]
